---
ID: "9df1896b-bbc1-4d92-b78a-e467b192860b"
Parent: "2af9514c-4fc4-41ef-b12a-658555e41247"
Template: "2af9514c-4fc4-41ef-b12a-658555e41247"
Path: /sitecore/templates/Foundation/Multisite/Datasource Settings Folder/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191121T071918Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
